Implement sessions and games so we can have multiplayer
ByteBuildersLabs/ByteBeastsBackend pull request #21
Opened 2024-09-02 02:22 UTC by RolandoDrRobot

This one resolves this https://github.com/ByteBuildersLabs/ByteBeastsBackend/issues/20

The idea is to implement the necessary models to have sessions and games where other can join to your game, this was developed in the game jam and was tested there, still need to implement in unity

### Testing and Build
<img width="871" alt="Captura de pantalla 2024-09-01 a la(s) 10 20 37 p  m" src="https://github.com/user-attachments/assets/783470ac-72df-4a38-afa1-02c2a79d5a70">

2024-09-02 03:26 UTC, coxmars commented
@RolandoDrRobot lgtm, sozo build and sozo test passed. I will review it in more detail tomorrow if you want 🫡

2024-09-02 05:11 UTC, danielcdz commented
In the PR we can use Closes #`issue` see this comment: https://github.com/ByteBuildersLabs/ByteBeastsBackend/pull/15#issuecomment-2323823936

2024-09-02 05:12 UTC, danielcdz commented
I will review the code in detail tomorrow sir @RolandoDrRobot 🫡

2024-09-02 21:28 UTC, coxmars requested changes
Hi @RolandoDrRobot, LGTM just resolve the conflits and we are done 🫡

2024-09-04 02:18 UTC, danielcdz commented on src/models.cairo
Why are we adding this models file after the refactor @coxmars did, which involved splitting the models into separate files?

2024-09-04 02:18 UTC, danielcdz commented on src/models/GamePlayer.cairo
We don't want to add a test to this model?

2024-09-04 02:18 UTC, danielcdz commented on src/systems/realms.cairo
I'm not 100% sure but I think we can rename the dojo contract to be different from the actions.cairo one and avoid any issue with the naming, as both contracts are going to have the same name

2024-09-04 02:38 UTC, coxmars approved these changes
Conflicts have been resolved, but I'd like to know the responses to Daniel's feedback 🫡

2024-09-07 19:40 UTC, coxmars approved these changes
LGTM 🫡

2024-09-07 19:48 UTC, danielcdz approved these changes
LGTM

2024-09-07 21:02 UTC, merged