feat-documentation
ByteBuildersLabs/ByteBeastsBackend pull request #84
Opened 2024-10-26 21:25 UTC by KevinMB0220

## Pull Request Overview
### 📝 Summary 
- Closes #(issue)
- 
### 🔄 Changes Made
- 
### 🔧 Tests Results
- 

### 🔜 Next Steps
- 
PoC inicial

2024-10-27 21:59 UTC, coxmars commented on src/systems/battle.cairo
> -            //TODO: extend with effectivity by type, randomness, etc
@KevinMB0220, please keep the existing comments as they serve as a guide for future improvements in specific sections. You can add any new comments alongside them.

2024-10-27 22:00 UTC, coxmars commented on src/systems/battle.cairo
> -            // TODO: investigate how can we make It random
Same applies here

2024-10-28 02:18 UTC, danielcdz requested changes

2024-10-28 02:18 UTC, danielcdz commented on src/models/battle.cairo
> +/// Defines the `Battle` struct, which represents a battle between two players.
can you replace the word `struct` to `model`?

2024-10-28 02:18 UTC, danielcdz commented on src/models/battle.cairo
> +    // ***************************************************************
Can you move to the top of the test? place it in line 40, in most of this tests for models we do testing for the initialization of the model, so I think is better to leave it on the top level

2024-10-28 02:18 UTC, danielcdz commented on src/models/battle.cairo
> +    // Imports the `Battle` struct from the `bytebeasts` models.
for imports we can avoid the comments since are very intuitive

2024-10-28 02:18 UTC, danielcdz commented on src/models/battle.cairo
> +        // Asserts to check if the `battle` instance has the expected values.
this also can be avoided

2024-10-28 02:18 UTC, danielcdz commented on src/models/battle.cairo
> +        // Creates an instance of `Battle` with predefined values for testing.
this can be avoided

2024-10-28 02:18 UTC, danielcdz commented on src/systems/battle.cairo
> +    fn flee(ref world: IWorldDispatcher, battle_id: u32); // Attempts to flee
Can you change this to be on top of the function definition, for example:

``` rust
    // Executes an attack
    fn attack(ref world: IWorldDispatcher, battle_id: u32, mt_id: u32); 
   // Uses a potion
    fn use_potion(ref world: IWorldDispatcher, battle_id: u32, potion_id: u32); 

```

2024-10-28 02:18 UTC, danielcdz commented on src/systems/battle.cairo
> +// ***************************************************************
this can be avoided

2024-10-28 02:22 UTC, danielcdz commented
In some comments you are using `///` and in other `//` can you update all of them to be just `//`?

2024-10-29 18:40 UTC, KevinMB0220 commented
yes, I'm almost done pr @danielcdz

2024-10-29 18:58 UTC, closed without merging